install:
  - sudo apt-get update
  - sudo apt-get install -y cmake
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y openjdk-9-jre-headless
  - sudo apt-get install -y emscripten
script:
  # emscripten
  #- git clone https://github.com/juj/emsdk.git emsdk --depth=10
  #- cd emsdk
  #- ./emsdk update-tags
  #- ./emsdk install latest
  #- ./emsdk activate latest
  #- . emsdk_env.sh
  #- cd ..
  - emcc --version
  - emcc list
  
  # freetype
  - git clone git://git.sv.nongnu.org/freetype/freetype2.git freetype2 --depth=10
  - cp ./modules.cfg freetype2/modules.cfg
  #- cp ./exports.mk freetype2/builds/exports.mk
  - cp ./include/freetype/config/ftoption.h freetype2/include/freetype/config/ftoption.h
  - cp ./main.c freetype2/main.c
  - cd freetype2
  
  # build
  - ./autogen.sh
  - ./configure
  #- make
  #- emconfigure ./configure
  - emmake make
  - emcc -I ./include -o main.o main.c
  - emcc -O0 -s NO_EXIT_RUNTIME=1 \
    -s EXPORTED_FUNCTIONS='["_main","_load_font","_find_font","_get_bitmap","_get_left","_get_top","_get_width","_get_height","_get_pitch","_get_advance"]' \
    main.o -o freetype.js
